project:
  type: website
  render: 
    - "*.qmd"
    - "*.ipynb"
    
website:
  title: "DSAN5000_Project"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: https://github.com/anly501/dsan-5000-project-jtjt427/tree/main/codes
        text: Code
      - href: https://github.com/anly501/dsan-5000-project-jtjt427/tree/main/data
        text: Data
      - href: Introduction.qmd
        text: Introduction
      - href: Data_Gathering.qmd
        text: Data Gathering
      - href: Cleaning.ipynb
        text: Data Cleaning
      - href: Data_Exploration.ipynb
        text: Data Exploration
      - href: Clustering.qmd
        text: Clustering
      - href: Dimensionality_Reduction.qmd
        text: Dimensionality Reduction
      - text: Decision Trees
        menu: 
          - href: Classification.qmd
            text: Classification
          - href: Regression.qmd
            text: Regression
      - href: ARM.qmd
        text: ARM
      - href: Conclusions.qmd
        text: Conclusions
      - href: Naive_Bayes.ipynb
        text: Naive_Bayes
bibliography: references.bib
      

format:
  html:
    theme: cosmo
    toc: true



